// <auto-generated />
using System;
using KanbaniteAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanbaniteAPI.Migrations
{
    [DbContext(typeof(KanbaniteDbContext))]
    [Migration("20250724204346_DefaultTaskStateFixture")]
    partial class DefaultTaskStateFixture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KanbaniteAPI.Entity.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Shorthand")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shorthand");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("KanbaniteAPI.Entity.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("TaskStateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("task_state_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_tasks_project_id");

                    b.HasIndex("TaskStateId")
                        .HasDatabaseName("ix_tasks_task_state_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("KanbaniteAPI.Entity.TaskState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks_states");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_tasks_states_project_id");

                    b.ToTable("tasks_states", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5565ef4f-0b8f-4f0b-88f4-c5211f367543"),
                            Name = "Open"
                        });
                });

            modelBuilder.Entity("KanbaniteAPI.Entity.TaskItem", b =>
                {
                    b.HasOne("KanbaniteAPI.Entity.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_tasks_projects_project_id");

                    b.HasOne("KanbaniteAPI.Entity.TaskState", "TaskState")
                        .WithMany()
                        .HasForeignKey("TaskStateId")
                        .HasConstraintName("fk_tasks_tasks_states_task_state_id");

                    b.Navigation("Project");

                    b.Navigation("TaskState");
                });

            modelBuilder.Entity("KanbaniteAPI.Entity.TaskState", b =>
                {
                    b.HasOne("KanbaniteAPI.Entity.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_tasks_states_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KanbaniteAPI.Entity.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
