services:
  kanbanite-api:
    image: kanbaniteapi
    build:
      context: .
      dockerfile: KanbaniteAPI/Dockerfile
    networks:
      - kanbanite_network
  
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanbanite
    ports:
      - "3307:3306"
    networks:
      - kanbanite_network

networks:
  kanbanite_network:
    driver: bridge