services:
  kanbanite-api:
    image: kanbaniteapi
    build:
      context: .
      dockerfile: KanbaniteAPI/Dockerfile
    networks:
      - kanbanite_network
  
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_USER: kanbanite_admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: kanbanite
    ports:
      - "3306:3306"
    networks:
      - kanbanite_network

networks:
  kanbanite_network:
    driver: bridge